name: CI - ASP.NET Core WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar SDK do .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # ou a versão usada no seu projeto

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar solução
      run: dotnet build --configuration Release --no-restore

    - name: Executar testes
      run: dotnet test --no-build --verbosity normal

    - name: Publicar aplicação
      run: dotnet publish --configuration Release --output ./publish

