name: Build and Deploy .NET WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar o .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restaurar dependências
      run: dotnet restore ./github4women/github4women.csproj

    - name: Compilar projeto
      run: dotnet build ./github4women/github4women.csproj --configuration Release --no-restore

    - name: Executar testes (se houver)
      run: dotnet test ./github4women/github4women.csproj --no-build --verbosity normal

    - name: Publicar aplicação
      run: dotnet publish ./github4women/github4women.csproj --configuration Release --output ./publish

    - name: Exibir arquivos publicados
      run: ls -R ./publish

